title: BasWas.blog
description: The place on the internet where BasWas shares stuff.
remote_theme: sharadcodes/jekyll-theme-serial-programmer
markdown: kramdown
plugins:
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed